"""Golden cases sintéticos, transparentes e determinísticos.

Os dados não representam pessoas nem eventos reais. Eles foram desenhados para
exercitar sinais, contrafatos e falhas seguras do catálogo completo.
"""

from __future__ import annotations

import hashlib
from datetime import UTC, date, datetime, timedelta

from .models import (
    ActorType,
    ClientSnapshot,
    CoverageUniverse,
    ExecutionCapacity,
    FixedIncomeProduct,
    FixedIncomeReference,
    FixedIncomeTrade,
    LoadManifest,
    MarketCoverageSnapshot,
    OtcTrade,
    PositionSnapshot,
    RelationshipEdge,
    Side,
    SurveillanceDataset,
    TradeEvent,
)


def _dt(day: int, hour: int, minute: int = 0) -> datetime:
    return datetime(2026, 8, day, hour, minute, tzinfo=UTC)


def _client(
    client_id: str,
    profile: str,
    control: str,
    complexity: int,
    segment: str = "RETAIL",
) -> ClientSnapshot:
    return ClientSnapshot(
        client_id=client_id,
        valid_from=_dt(1, 0),
        segment=segment,
        risk_class="STANDARD",
        suitability_profile=profile,
        objective="CAPITAL_GROWTH" if profile != "CONSERVATIVE" else "CAPITAL_PRESERVATION",
        horizon_days=365,
        control_source=control,  # type: ignore[arg-type]
        complexity_limit=complexity,
    )


def build_demo_dataset() -> SurveillanceDataset:
    trades = (
        # Concentração recorrente e simétrica no universo observado.
        TradeEvent(
            trade_id="T-CONC-01",
            event_time=_dt(26, 14),
            instrument_id="INST-Z",
            client_id="CLIENT-A",
            account_id="ACC-A",
            advisor_id="ADV-1",
            counterparty_id="CP-X",
            side=Side.BUY,
            price=100,
            quantity=500,
            fees=20,
            reference_price=100,
            market_spread=0.5,
        ),
        TradeEvent(
            trade_id="T-CONC-02",
            event_time=_dt(26, 14, 20),
            instrument_id="INST-Z",
            client_id="CLIENT-A",
            account_id="ACC-A",
            advisor_id="ADV-1",
            counterparty_id="CP-X",
            side=Side.SELL,
            price=100.1,
            quantity=1_000,
            fees=20,
            reference_price=100,
            market_spread=0.5,
        ),
        TradeEvent(
            trade_id="T-CONC-03",
            event_time=_dt(27, 13),
            instrument_id="INST-Z",
            client_id="CLIENT-A",
            account_id="ACC-A",
            advisor_id="ADV-1",
            counterparty_id="CP-X",
            side=Side.BUY,
            price=99.9,
            quantity=500,
            fees=20,
            reference_price=100,
            market_spread=0.5,
        ),
        TradeEvent(
            trade_id="T-CONC-04",
            event_time=_dt(27, 13, 15),
            instrument_id="INST-Z",
            client_id="CLIENT-A",
            account_id="ACC-A",
            advisor_id="ADV-1",
            counterparty_id="CP-X",
            side=Side.SELL,
            price=100,
            quantity=1_000,
            fees=20,
            reference_price=100,
            market_spread=0.5,
        ),
        # Janela de fechamento: desvio + direção + participação + posição beneficiada.
        TradeEvent(
            trade_id="T-MANIP-01",
            event_time=_dt(28, 16, 50),
            instrument_id="INST-Z",
            client_id="CLIENT-A",
            account_id="ACC-A",
            advisor_id="ADV-1",
            counterparty_id="CP-X",
            side=Side.BUY,
            price=104.8,
            quantity=500,
            fees=25,
            reference_price=100,
            market_spread=0.5,
            position_before=10_000,
        ),
        TradeEvent(
            trade_id="T-MANIP-02",
            event_time=_dt(28, 16, 56),
            instrument_id="INST-Z",
            client_id="CLIENT-A",
            account_id="ACC-A",
            advisor_id="ADV-1",
            counterparty_id="CP-X",
            side=Side.BUY,
            price=105.2,
            quantity=500,
            fees=25,
            reference_price=100,
            market_spread=0.5,
            position_before=10_500,
        ),
        # Fluxo comparável para tornar o denominador explícito.
        TradeEvent(
            trade_id="T-COHORT-01",
            event_time=_dt(28, 16, 52),
            instrument_id="INST-Z",
            client_id="CLIENT-B",
            account_id="ACC-B",
            advisor_id="ADV-1",
            counterparty_id="CP-Y",
            side=Side.SELL,
            price=100.2,
            quantity=500,
            fees=10,
            reference_price=100,
            market_spread=0.5,
        ),
        # Atividade potencialmente excessiva: volume/equity, custo e reversões rápidas.
        *tuple(
            TradeEvent(
                trade_id=f"T-CHURN-{index:02d}",
                event_time=_dt(index, 12),
                instrument_id="INST-X",
                client_id="CLIENT-C",
                account_id="ACC-C",
                advisor_id="ADV-2",
                counterparty_id=None,
                side=Side.BUY if index % 2 else Side.SELL,
                price=100,
                quantity=1_000,
                fees=3_000,
                reference_price=100,
                market_spread=0.4,
            )
            for index in range(1, 9)
        ),
    )
    positions = (
        PositionSnapshot(
            account_id="ACC-A",
            client_id="CLIENT-A",
            instrument_id="INST-Z",
            as_of_time=_dt(28, 16),
            quantity=10_000,
            market_value=1_000_000,
            average_equity=2_000_000,
        ),
        PositionSnapshot(
            account_id="ACC-B",
            client_id="CLIENT-B",
            instrument_id="INST-Z",
            as_of_time=_dt(28, 16),
            quantity=-500,
            market_value=-50_000,
            average_equity=1_000_000,
        ),
        PositionSnapshot(
            account_id="ACC-C",
            client_id="CLIENT-C",
            instrument_id="INST-X",
            as_of_time=_dt(28, 16),
            quantity=0,
            market_value=0,
            average_equity=100_000,
        ),
    )
    clients = (
        _client("CLIENT-A", "MODERATE", "ADVISOR", 3),
        _client("CLIENT-B", "MODERATE", "CLIENT", 3),
        _client("CLIENT-C", "CONSERVATIVE", "UNKNOWN", 1),
        _client("CLIENT-D", "CONSERVATIVE", "ADVISOR", 1),
        _client("CLIENT-E", "SOPHISTICATED", "CLIENT", 5, segment="PRIVATE"),
    )
    otc_trades = (
        OtcTrade(
            structure_id="OTC-STRUCT-001",
            client_id="CLIENT-D",
            advisor_id="ADV-3",
            event_time=_dt(28, 15),
            underlying_id="IBOV",
            strategy_chain_id="CHAIN-OTC-1",
            notional=2_500_000,
            trade_premium=180_000,
            independent_value=100_000,
            model_uncertainty=10_000,
            liquidity_band=15_000,
            model_id="LOCAL_VOL",
            model_version="2.1.0",
            market_snapshot_id="MKT-20260828-1500",
            product_complexity=4,
            rolled_from="OTC-STRUCT-000",
        ),
        OtcTrade(
            structure_id="OTC-STRUCT-002",
            client_id="CLIENT-E",
            advisor_id="ADV-4",
            event_time=_dt(28, 15, 10),
            underlying_id="USD-BRL",
            strategy_chain_id="CHAIN-OTC-2",
            notional=1_000_000,
            trade_premium=50_000,
            independent_value=None,
            model_uncertainty=None,
            liquidity_band=8_000,
            product_complexity=5,
        ),
    )
    fixed_income_trades = (
        FixedIncomeTrade(
            trade_id="FI-CLIENT-01",
            event_time=_dt(28, 10),
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            issuer_id="ISSUER-ALPHA",
            buyer_party_id="CLIENT-FI",
            buyer_actor_type=ActorType.CLIENT,
            seller_party_id="TREASURY-DESK",
            seller_actor_type=ActorType.TREASURY_PROP,
            buyer_account_id="ACC-FI",
            execution_capacity=ExecutionCapacity.PRINCIPAL,
            desk_id="DESK-RF",
            book_id="BOOK-CREDIT",
            trader_id="TRADER-01",
            price_unit=101.20,
            quantity=100,
            financial_value=101_200,
            yield_rate=0.135,
            spread_bps=320,
            duration_years=3.2,
            dv01=32.4,
        ),
        FixedIncomeTrade(
            trade_id="FI-CLIENT-02",
            event_time=_dt(28, 10, 10),
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            issuer_id="ISSUER-ALPHA",
            buyer_party_id="CLIENT-FI",
            buyer_actor_type=ActorType.CLIENT,
            seller_party_id="TREASURY-DESK",
            seller_actor_type=ActorType.TREASURY_PROP,
            buyer_account_id="ACC-FI",
            execution_capacity=ExecutionCapacity.PRINCIPAL,
            desk_id="DESK-RF",
            book_id="BOOK-CREDIT",
            trader_id="TRADER-01",
            price_unit=101.50,
            quantity=120,
            financial_value=121_800,
            yield_rate=0.136,
            spread_bps=330,
            duration_years=3.2,
            dv01=38.9,
        ),
        FixedIncomeTrade(
            trade_id="FI-CLIENT-03",
            event_time=_dt(28, 10, 20),
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            issuer_id="ISSUER-ALPHA",
            buyer_party_id="CLIENT-FI",
            buyer_actor_type=ActorType.CLIENT,
            seller_party_id="TREASURY-DESK",
            seller_actor_type=ActorType.TREASURY_PROP,
            buyer_account_id="ACC-FI",
            execution_capacity=ExecutionCapacity.PRINCIPAL,
            desk_id="DESK-RF",
            book_id="BOOK-CREDIT",
            trader_id="TRADER-01",
            price_unit=101.80,
            quantity=130,
            financial_value=132_340,
            yield_rate=0.137,
            spread_bps=340,
            duration_years=3.2,
            dv01=42.1,
        ),
        *tuple(
            FixedIncomeTrade(
                trade_id=f"FI-MARKET-{index:02d}",
                event_time=_dt(28, 10, 1 + index * 6),
                instrument_id="DEB-ALPHA",
                product_type=FixedIncomeProduct.DEBENTURE,
                issuer_id="ISSUER-ALPHA",
                buyer_party_id=f"INSTITUTION-{index}",
                buyer_actor_type=ActorType.INSTITUTION,
                seller_party_id=f"MARKET-MAKER-{index}",
                seller_actor_type=ActorType.MARKET_MAKER,
                execution_capacity=ExecutionCapacity.PRINCIPAL,
                price_unit=100.10 + index * 0.15,
                quantity=75,
                financial_value=(100.10 + index * 0.15) * 75,
                yield_rate=0.12,
                spread_bps=150,
            )
            for index in range(4)
        ),
    )
    fixed_income_references = (
        FixedIncomeReference(
            reference_id="FI-REF-0959",
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            reference_time=_dt(28, 9, 59),
            source="SYNTHETIC_COMPOSITE",
            methodology_version="1.0.0",
            price_unit=100.00,
            yield_rate=0.120,
            spread_bps=150,
            benchmark_curve_id="DI-PRE",
        ),
        FixedIncomeReference(
            reference_id="FI-REF-1005",
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            reference_time=_dt(28, 10, 5),
            source="SYNTHETIC_COMPOSITE",
            methodology_version="1.0.0",
            price_unit=100.25,
            yield_rate=0.119,
            spread_bps=145,
            benchmark_curve_id="DI-PRE",
        ),
        FixedIncomeReference(
            reference_id="FI-REF-1009",
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            reference_time=_dt(28, 10, 9),
            source="SYNTHETIC_COMPOSITE",
            methodology_version="1.0.0",
            price_unit=100.25,
            yield_rate=0.119,
            spread_bps=145,
            benchmark_curve_id="DI-PRE",
        ),
        FixedIncomeReference(
            reference_id="FI-REF-1015",
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            reference_time=_dt(28, 10, 15),
            source="SYNTHETIC_COMPOSITE",
            methodology_version="1.0.0",
            price_unit=100.55,
            yield_rate=0.118,
            spread_bps=140,
            benchmark_curve_id="DI-PRE",
        ),
        FixedIncomeReference(
            reference_id="FI-REF-1019",
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            reference_time=_dt(28, 10, 19),
            source="SYNTHETIC_COMPOSITE",
            methodology_version="1.0.0",
            price_unit=100.55,
            yield_rate=0.118,
            spread_bps=140,
            benchmark_curve_id="DI-PRE",
        ),
        FixedIncomeReference(
            reference_id="FI-REF-1025",
            instrument_id="DEB-ALPHA",
            product_type=FixedIncomeProduct.DEBENTURE,
            reference_time=_dt(28, 10, 25),
            source="SYNTHETIC_COMPOSITE",
            methodology_version="1.0.0",
            price_unit=100.90,
            yield_rate=0.117,
            spread_bps=135,
            benchmark_curve_id="DI-PRE",
        ),
    )
    market_coverage = (
        MarketCoverageSnapshot(
            instrument_id="DEB-ALPHA",
            window_start=_dt(28, 9),
            window_end=_dt(28, 18),
            source="SYNTHETIC_REGULATORY_FEED",
            universe=CoverageUniverse.REGULATORY_REPORTED,
            coverage_ratio=0.95,
            observed_record_count=len(fixed_income_trades),
            expected_record_count=len(fixed_income_trades),
        ),
    )
    relationships = (
        RelationshipEdge(
            from_id="CLIENT-A",
            to_id="ADV-1",
            relation_type="ADVISED_BY",
            valid_from=_dt(1, 0),
            observed_at=_dt(28, 20),
            source="CRM",
            confidence=1,
        ),
        RelationshipEdge(
            from_id="CLIENT-B",
            to_id="ADV-1",
            relation_type="ADVISED_BY",
            valid_from=_dt(1, 0),
            observed_at=_dt(28, 20),
            source="CRM",
            confidence=1,
        ),
        RelationshipEdge(
            from_id="CLIENT-A",
            to_id="GROUP-G1",
            relation_type="BELONGS_TO_GROUP",
            valid_from=_dt(1, 0),
            observed_at=_dt(28, 20),
            source="KYC",
            confidence=1,
        ),
        RelationshipEdge(
            from_id="CLIENT-D",
            to_id="ADV-3",
            relation_type="ADVISED_BY",
            valid_from=_dt(1, 0),
            observed_at=_dt(28, 20),
            source="CRM",
            confidence=1,
        ),
    )
    gross_notional = sum(trade.notional for trade in trades)
    manifest = LoadManifest(
        source_system="SYNTHETIC_GOLDEN_CASES",
        source_extract_id="DEMO-20260828",
        contract_version="1.0.0",
        business_date=date(2026, 8, 28),
        expected_record_count=len(trades),
        expected_gross_notional=gross_notional,
        expected_fixed_income_record_count=len(fixed_income_trades),
        expected_fixed_income_financial_value=sum(
            trade.financial_value for trade in fixed_income_trades
        ),
        sha256=hashlib.sha256(b"vertice-demo-20260828").hexdigest(),
    )
    return SurveillanceDataset(
        snapshot_id="SNAPSHOT-DEMO-20260828",
        as_of=_dt(28, 23, 59),
        trades=trades,
        positions=positions,
        clients=clients,
        otc_trades=otc_trades,
        fixed_income_trades=fixed_income_trades,
        fixed_income_references=fixed_income_references,
        market_coverage=market_coverage,
        relationships=relationships,
        manifest=manifest,
    )


def build_benign_dataset() -> SurveillanceDataset:
    trades = (
        TradeEvent(
            trade_id="T-BENIGN-01",
            event_time=_dt(28, 11),
            instrument_id="LIQUID-ETF",
            client_id="CLIENT-BENIGN",
            account_id="ACC-BENIGN",
            counterparty_id="CP-1",
            side=Side.BUY,
            price=100,
            quantity=10,
            fees=1,
            reference_price=100,
            market_spread=0.1,
        ),
        TradeEvent(
            trade_id="T-BENIGN-02",
            event_time=_dt(28, 12),
            instrument_id="LIQUID-ETF",
            client_id="CLIENT-BENIGN",
            account_id="ACC-BENIGN",
            counterparty_id="CP-2",
            side=Side.SELL,
            price=100.05,
            quantity=5,
            fees=1,
            reference_price=100,
            market_spread=0.1,
        ),
    )
    client = _client("CLIENT-BENIGN", "MODERATE", "CLIENT", 3)
    position = PositionSnapshot(
        account_id="ACC-BENIGN",
        client_id="CLIENT-BENIGN",
        instrument_id="LIQUID-ETF",
        as_of_time=_dt(28, 16),
        quantity=5,
        market_value=500,
        average_equity=1_000_000,
    )
    fixed_income_trades = tuple(
        FixedIncomeTrade(
            trade_id=f"FI-BENIGN-{index}",
            event_time=_dt(28, 13, index * 5),
            instrument_id="DEB-BENIGN",
            product_type=FixedIncomeProduct.DEBENTURE,
            issuer_id="ISSUER-BENIGN",
            buyer_party_id=f"CLIENT-BENIGN-FI-{index}",
            buyer_actor_type=ActorType.CLIENT,
            seller_party_id=f"INSTITUTION-BENIGN-{index}",
            seller_actor_type=ActorType.INSTITUTION,
            execution_capacity=ExecutionCapacity.AGENCY,
            price_unit=100.0,
            quantity=10,
            financial_value=1_000,
            yield_rate=0.11,
            spread_bps=100,
        )
        for index in range(3)
    )
    fixed_income_references = tuple(
        FixedIncomeReference(
            reference_id=f"FI-REF-BENIGN-{index}",
            instrument_id="DEB-BENIGN",
            product_type=FixedIncomeProduct.DEBENTURE,
            reference_time=_dt(28, 12, 59) + timedelta(minutes=index * 5),
            source="SYNTHETIC_COMPOSITE",
            methodology_version="1.0.0",
            price_unit=100.0,
            yield_rate=0.11,
            spread_bps=100,
        )
        for index in range(4)
    )
    market_coverage = (
        MarketCoverageSnapshot(
            instrument_id="DEB-BENIGN",
            window_start=_dt(28, 12),
            window_end=_dt(28, 14),
            source="SYNTHETIC_REGULATORY_FEED",
            universe=CoverageUniverse.REGULATORY_REPORTED,
            coverage_ratio=1,
            observed_record_count=3,
            expected_record_count=3,
        ),
    )
    return SurveillanceDataset(
        snapshot_id="SNAPSHOT-BENIGN-20260828",
        as_of=_dt(28, 23, 59),
        trades=trades,
        clients=(client,),
        positions=(position,),
        fixed_income_trades=fixed_income_trades,
        fixed_income_references=fixed_income_references,
        market_coverage=market_coverage,
    )
